name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Setup Firebase Service Account
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CAMP_MAPPING_APP }}' > ./firebase-service-account.json
        env:
          FIREBASE_SERVICE_ACCOUNT_CAMP_MAPPING_APP: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CAMP_MAPPING_APP }}

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT_ID }} --token "$(firebase login:ci --project ${{ secrets.FIREBASE_PROJECT_ID }})"
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
